// <auto-generated />
namespace VideoRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class populateGenreId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateGenreId));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201016132_populateGenreId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
